export const initBoard = [
  { playerId: 1, id: 1, count: 9, hover: false, tuzdyq: false },
  { playerId: 1, id: 2, count: 9, hover: false, tuzdyq: false },
  { playerId: 1, id: 3, count: 9, hover: false, tuzdyq: false },
  { playerId: 1, id: 4, count: 9, hover: false, tuzdyq: false },
  { playerId: 1, id: 5, count: 9, hover: false, tuzdyq: false },
  { playerId: 1, id: 6, count: 9, hover: false, tuzdyq: false },
  { playerId: 1, id: 7, count: 9, hover: false, tuzdyq: false },
  { playerId: 1, id: 8, count: 9, hover: false, tuzdyq: false },
  { playerId: 1, id: 9, count: 9, hover: false, tuzdyq: false },
  { playerId: 0, id: 1, count: 9, hover: false, tuzdyq: false },
  { playerId: 0, id: 2, count: 9, hover: false, tuzdyq: false },
  { playerId: 0, id: 3, count: 9, hover: false, tuzdyq: false },
  { playerId: 0, id: 4, count: 9, hover: false, tuzdyq: false },
  { playerId: 0, id: 5, count: 9, hover: false, tuzdyq: false },
  { playerId: 0, id: 6, count: 9, hover: false, tuzdyq: false },
  { playerId: 0, id: 7, count: 9, hover: false, tuzdyq: false },
  { playerId: 0, id: 8, count: 9, hover: false, tuzdyq: false },
  { playerId: 0, id: 9, count: 9, hover: false, tuzdyq: false },
];
